# -*- coding: utf-8 -*-
"""plots_example

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19Mn3_M8MssBC4PJCyjhHnDexhWj094-P
"""

import numpy as np
import pandas as pd

# Corrected sample data (all length=10)
np.random.seed(42)
x = np.arange(10)
y = np.random.rand(10)
categories = np.random.choice(['A', 'B', 'C'], size=10)  # Now length=10
values = np.random.randint(1, 100, 10)

df = pd.DataFrame({
    'x': x,
    'y': y,
    'category': categories,
    'value': values
})

# Line Plot
plt.plot(x, y, marker='o', label='Trend')
plt.title("Line Plot Example")
plt.legend()
plt.show()

# Bar Chart
plt.bar(x, y, color='skyblue')
plt.title("Bar Chart Example")
plt.show()

# Histogram
plt.hist(y, bins=5, edgecolor='black')
plt.title("Histogram Example")
plt.show()

# Regression Plot
sns.lmplot(x='x', y='y', data=df, ci=None)
plt.title("Seaborn Regression Plot")
plt.show()

# Heatmap
# Calculate correlation only for numeric columns
corr_matrix = df.select_dtypes(include=['number']).corr()
sns.heatmap(corr_matrix, annot=True, cmap='coolwarm')
plt.title("Numeric Columns Heatmap")
plt.show()

# Violin Plot
sns.violinplot(x='category', y='value', data=df)
plt.title("Violin Plot Example")
plt.show()

# Interactive Scatter Plot
fig = px.scatter(df, x='x', y='y', color='category', size='value',
                 title="Plotly Interactive Scatter")
fig.show()

# 3D Scatter (Bonus)
fig = px.scatter_3d(df, x='x', y='y', z='value', color='category')
fig.show()

